# Generated by Django 6.1.1 on 2026-09-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_pics/', verbose_name='Обложка категории (для главной)'),
        ),
    ]
