# Generated by Django 6.1.1 on 2026-09-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Расскажите покупателю об особенностях этой категории товаров на главной странице', null=True, verbose_name='Описание для главного баннера'),
        ),
    ]
